export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <p
          style={{
            backgroundColor: "lightblue",
            color: "black",
            height: "5rem",
          }}
        >
          Header``
        </p>
        <div style={{ padding: "1rem", border: "1px solid black" }}>
          {children}
        </div>
        <p
          style={{
            backgroundColor: "lightgreen",
            color: "black",
            height: "5rem",
          }}
        >
          Footer
        </p>
      </body>
    </html>
  );
}
